# docker build tests/ -f tests/Dockerfile.darknet-cpu -t upload.rocks.canonical.com:5000/kubeflow/examples/darknet-cpu:latest
# docker push upload.rocks.canonical.com:5000/kubeflow/examples/darknet-cpu:latest

FROM ubuntu:18.04 as compile

ENV DEBIAN_FRONTEND=noninteractive

RUN apt update \
 && apt install -y git libopencv-dev pkg-config \
 && rm -rf /var/lib/apt/lists/*

RUN git clone https://github.com/pjreddie/darknet.git \
 && cd darknet \
 && make OPENCV=1 OPENMP=1

FROM ubuntu:18.04

COPY --from=compile /darknet/darknet /usr/bin
COPY --from=compile /darknet/cfg /cfg
COPY --from=compile /darknet/data /data

RUN apt update \
 && apt install -y \
        libopencv-highgui3.2 \
        libopencv-imgcodecs3.2 \
        libopencv-videoio3.2 \
 && rm -rf /var/lib/apt/lists/*

ENTRYPOINT ['/usr/bin/darknet']

CMD ['detect', '/cfg/yolov3.cfg', '/weights', 'dog.png']